import AdminCategoryTree, { categoryMatches } from "../../components/AdminCategoryTree";

const sizeGroupLabels = { clothing: "Базовая одежда", women_clothing: "Женская одежда", men_clothing: "Мужская одежда", tops: "Международные размеры", women_dress: "Платья", women_trousers: "Женские брюки", men_trousers: "Мужские брюки", waist: "Джинсы · базовая сетка", jeans: "Джинсы · полная сетка", accessory: "Аксессуары", belt: "Ремни", headwear: "Головные уборы", shoes: "Обувь" };

export default function AdminStockPanel({
  products, categoryTree, stockCategory, setStockCategory, stockCategoryProducts,
  stockProductId, setStockProductId, selectedStock, stockDraft, setStockDraft,
  stockOptions, newVariant, setNewVariant, expectedSizeType, allowedStockSizes,
  onAddVariant, onRemoveVariant, onSave,
}) {
  return <div className="stock-panel">
    <div className="stock-picker"><p className="page-kicker">Склад</p><h2>Управление остатками</h2>
      <AdminCategoryTree tree={categoryTree} selected={stockCategory} onSelect={(category) => { setStockCategory(category); const first = products.find((item) => categoryMatches(categoryTree, category, item.categories || [])); setStockProductId(first?.id || ""); }} selectBranches title="Сначала выберите категорию" />
      <label className="stock-product-select">Товар<select value={stockProductId} onChange={(e) => setStockProductId(e.target.value)} disabled={!stockCategoryProducts.length}><option value="">Выберите товар</option>{stockCategoryProducts.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label>
      {!stockCategoryProducts.length && <p className="stock-category-empty">В этой категории пока нет товаров.</p>}
      {selectedStock && <div className="stock-product"><img src={selectedStock.imageUrl} alt="" /><div><strong>{selectedStock.name}</strong><small>{selectedStock.categories?.join(" › ")}</small><span>Вариантов: {stockDraft.length} · всего {stockDraft.reduce((sum, item) => sum + Number(item.quantity || 0), 0)} шт.</span></div></div>}
    </div>
    <div className="stock-workspace">{selectedStock ? <><section className="stock-add"><div><p className="page-kicker">Новый вариант</p><h3>Добавить цвет и размер</h3><small>Сетка: {sizeGroupLabels[expectedSizeType] || expectedSizeType}</small></div><div className="stock-color-field"><span>Цвет</span><div className="stock-color-options">{stockOptions.colors.map((color) => <button type="button" className={String(newVariant.colorId) === String(color.id) ? "selected" : ""} onClick={() => setNewVariant({ ...newVariant, colorId: color.id })} key={color.id} title={color.name} aria-label={`Цвет ${color.name}`}><i style={{ background: color.hexCode }} /><small>{color.name}</small></button>)}</div></div><label>Размер<select value={newVariant.sizeId} onChange={(e) => setNewVariant({ ...newVariant, sizeId: e.target.value })}>{allowedStockSizes.map((size) => <option value={size.id} key={size.id}>{size.name}{size.description ? ` · ${size.description}` : ""}</option>)}</select></label><label>Количество<input type="number" min="0" value={newVariant.quantity} onChange={(e) => setNewVariant({ ...newVariant, quantity: e.target.value })} /></label><button type="button" className="stock-add__button" onClick={onAddVariant}>Добавить вариант</button></section><div className="stock-grid"><div className="stock-row stock-row--head"><span>Цвет</span><span>Размер</span><span>Количество</span><span></span></div>{stockDraft.length === 0 && <p className="stock-empty">У товара пока нет вариантов. Добавьте размер и цвет выше.</p>}{stockDraft.map((row, index) => <div className="stock-row" key={`${row.colorId}-${row.sizeId}`}><span className="stock-color"><i style={{ background: stockOptions.colors.find((color) => String(color.id) === String(row.colorId))?.hexCode }} />{row.colorName}</span><span><strong>{row.sizeName}</strong><small>{sizeGroupLabels[row.sizeType] || row.sizeType || "Размер"}</small></span><input type="number" min="0" value={row.quantity} onChange={(e) => setStockDraft(stockDraft.map((item, i) => i === index ? { ...item, quantity: e.target.value } : item))} /><button type="button" className="stock-remove" onClick={() => onRemoveVariant(index)} aria-label={`Удалить ${row.colorName}, размер ${row.sizeName}`}>Удалить</button></div>)}<div className="stock-save"><span>Удалённые строки исчезнут полностью после сохранения.</span><button className="primary-action" onClick={onSave}>Сохранить остатки</button></div></div></> : <div className="stock-workspace-empty"><strong>Выберите категорию и товар</strong><span>Здесь появятся цвета, размеры и количество.</span></div>}</div>
  </div>;
}
