spring.application.name=sunset
server.port=8081

spring.datasource.url=jdbc:postgresql://postgres_db:5432/sunset
spring.datasource.username=defuziq
spring.datasource.password=951753
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=postgresql
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:/db/changelog/changelog-master.xml
spring.liquibase.enabled=false

spring.security.jwt.secret=mySuperSecretKey
spring.security.jwt.expirationMs=86400000

logging.level.root=INFO
logging.level.com.sunset.auth.config=DEBUG
