services:
  postgres:
    image: postgres:13.15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: defuziq
      POSTGRES_PASSWORD: 951753
      POSTGRES_DB: sunset
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: defuziq@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 951753
    ports:
      - "5050:80"
    depends_on:
      - postgres

  api-gateway:
    container_name: api-gateway
    image: api-gateway:latest
    build:
      context: ./backend/api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - product-service
      - order-service
      - auth-service

  auth-service:
    container_name: auth-service
    image: auth-service:latest
    build:
      context: ./backend/auth-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  product-service:
    container_name: product-service
    image: product-service:latest
    build:
      context: ./backend/product-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - auth-service

  order-service:
    container_name: order-service
    image: order-service:latest
    build:
      context: ./backend/order-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - product-service
      - auth-service

volumes:
  postgres_data:
