server:
  port: 8080

spring:
  application:
    name: sunset
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**
        - id: product-service
          uri: http://product-service:8082
          predicates:
            - Path=/products/**
        - id: order-service
          uri: http://order-service:8083
          predicates:
            - Path=/order/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

jwt:
  secret: MySuperSecretKeyThatIsAtLeast32BytesLong!!
  expirationMs: 86400000

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG

security:
  whitelist-paths:
    - /auth/register
    - /auth/login
    - /products/all
    - /products/by-uuid

