/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Регистрация клиента */
        post: operations["registerCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход */
        post: operations["loginCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Профиль текущего клиента */
        get: operations["getProfile"];
        /** Изменить профиль */
        put: operations["updateProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/profile/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Сменить пароль */
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Каталог */
        get: operations["listProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/by-uuid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Карточка товара по UUID */
        post: operations["getProductByUuid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/categories/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Дерево категорий */
        get: operations["getCategoryTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Оформить заказ
         * @description Повтор с тем же непустым idempotencyKey для клиента возвращает прежний заказ. Цена и остаток проверяются сервером.
         */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Мои заказы */
        get: operations["listMyOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/my/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        /** Подробности заказа */
        get: operations["getMyOrder"];
        /** Изменить получателя или получение до подтверждения */
        put: operations["updatePendingOrder"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/my/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отменить заказ */
        post: operations["cancelMyOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/promotions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Активные акции */
        get: operations["listPromotions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/promo/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Проверить промокод */
        post: operations["validatePromo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Message: {
            message?: string;
        };
        ApiError: {
            /** @description Стабильный машинный код, например BAD_REQUEST, NOT_FOUND или INVALID_TOKEN */
            code: string;
            message: string;
            fieldErrors: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            requestId: string;
            /** Format: date-time */
            timestamp: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            firstName: string;
            lastName: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        AuthResponse: {
            /** Format: uuid */
            uuid: string;
            /** Format: email */
            email: string;
            firstName?: string;
            lastName?: string;
            phone?: string | null;
            role: string;
            /** @description JWT после входа; null при регистрации */
            token: string | null;
        };
        UserProfile: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            firstName?: string;
            lastName?: string;
            phone?: string | null;
            /** Format: date */
            birthday?: string | null;
            avatar?: string | null;
            role: string;
        };
        UpdateProfileRequest: {
            /** Format: email */
            email: string;
            firstName: string;
            lastName: string;
            phone?: string;
            /** Format: date */
            birthday?: string;
            avatar?: string;
        };
        ChangePasswordRequest: {
            /** Format: password */
            currentPassword: string;
            /** Format: password */
            newPassword: string;
        };
        ProductUuidRequest: {
            /** Format: uuid */
            id: string;
        };
        Product: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string | null;
            price: number;
            gender?: string | null;
            imageUrl?: string | null;
            rating?: number;
            reviewCount?: number;
            categories?: string[];
            colors?: components["schemas"]["ProductColor"][];
            stock?: components["schemas"]["ProductStock"][];
        };
        ProductColor: {
            /** Format: uuid */
            id?: string;
            name?: string;
            hexCode?: string;
        };
        ProductStock: {
            /** Format: uuid */
            sizeId?: string;
            sizeName?: string;
            sizeType?: string;
            sizeGender?: string;
            sizeDescription?: string;
            /** Format: uuid */
            colorId?: string;
            colorName?: string;
            quantity?: number;
        };
        OrderItemRequest: {
            /** Format: uuid */
            productId: string;
            /** Format: uuid */
            colorId: string;
            /** Format: uuid */
            sizeId: string;
            quantity: number;
        };
        CreateOrderRequest: {
            customerName?: string;
            /** Format: email */
            customerEmail?: string;
            /** @description Если не передан, сервер берёт телефон из профиля; в итоге телефон обязателен */
            customerPhone?: string;
            /** @description Адрес доставки или название/адрес магазина самовывоза */
            address: string;
            /** @enum {string} */
            deliveryMethod?: "courier" | "pickup";
            /** @enum {string} */
            paymentMethod?: "CARD" | "SBP" | "ON_RECEIPT";
            /** @description Ключ идемпотентности передаётся в JSON-теле, не в HTTP-заголовке */
            idempotencyKey?: string;
            promoCode?: string;
            bonusesToUse?: number;
            items: components["schemas"]["OrderItemRequest"][];
        };
        Order: {
            /** Format: uuid */
            id: string;
            orderNumber: string;
            /** Format: uuid */
            userId?: string;
            customerName?: string;
            customerEmail?: string;
            customerPhone?: string;
            /** @enum {string} */
            status: "PENDING" | "CONFIRMED" | "ASSEMBLING" | "SHIPPED" | "DELIVERED" | "CANCELLED";
            subtotal?: number;
            discountAmount?: number;
            bonusesUsed?: number;
            bonusesEarned?: number;
            promoCode?: string | null;
            totalAmount: number;
            /** Format: date-time */
            createdAt?: string;
            items?: components["schemas"]["OrderItem"][];
        };
        OrderDetail: components["schemas"]["Order"] & {
            delivery?: {
                [key: string]: unknown;
            } | null;
            payment?: {
                [key: string]: unknown;
            } | null;
            returns?: {
                [key: string]: unknown;
            }[];
            events?: {
                [key: string]: unknown;
            }[];
        };
        OrderItem: {
            /** Format: uuid */
            productId?: string;
            /** Format: uuid */
            colorId?: string;
            colorName?: string | null;
            /** Format: uuid */
            sizeId?: string;
            sizeName?: string | null;
            name?: string;
            imageUrl?: string;
            quantity?: number;
            price?: number;
        };
        UpdatePendingOrderRequest: {
            customerName?: string;
            /** Format: email */
            customerEmail?: string;
            customerPhone?: string;
            address: string;
            /** @enum {string} */
            deliveryMethod?: "courier" | "pickup";
        };
        Promotion: {
            /** Format: uuid */
            id?: string;
            code?: string;
            title?: string;
            description?: string;
            discountPercent?: number;
            bonusMultiplier?: number;
            minOrder?: number;
            birthdayOnly?: boolean;
            /** Format: date-time */
            validUntil?: string | null;
        };
        ValidatePromoRequest: {
            code: string;
            subtotal?: number;
        };
    };
    responses: {
        /** @description Нет токена, JWT неверен или указаны неверные учётные данные */
        Unauthorized: {
            headers: {
                /** @description Доверенный ID запроса */
                "X-Request-Id"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Некорректный запрос */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Ресурс не найден */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        OrderId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Создан аккаунт; JWT выдаётся при последующем входе */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    loginCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Выдан JWT */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Профиль */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Обновлённый профиль */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Пароль изменён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список товаров */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"][];
                };
            };
        };
    };
    getProductByUuid: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUuidRequest"];
            };
        };
        responses: {
            /** @description Товар */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getCategoryTree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Дерево категорий */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Заказ создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listMyOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Заказы клиента */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMyOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Заказ, состав, получение, оплата и события */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updatePendingOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePendingOrderRequest"];
            };
        };
        responses: {
            /** @description Обновлённый заказ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    cancelMyOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Отменённый заказ; повторная отмена безопасна */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listPromotions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Акции */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Promotion"][];
                };
            };
        };
    };
    validatePromo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidatePromoRequest"];
            };
        };
        responses: {
            /** @description Данные применимого промокода */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
