/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Регистрация клиента */
        post: operations["registerCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход */
        post: operations["loginCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Профиль текущего клиента */
        get: operations["getProfile"];
        /** Изменить профиль */
        put: operations["updateProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/profile/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Сменить пароль */
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Каталог */
        get: operations["listProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/admin/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Справочник цветов и размеров для управления остатками */
        get: operations["listAdminVariants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/by-uuid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Карточка товара по UUID */
        post: operations["getProductByUuid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/categories/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Дерево категорий */
        get: operations["getCategoryTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/reviews/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        /** Отзывы о товаре */
        get: operations["listProductReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/review/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать или обновить свой отзыв */
        post: operations["saveProductReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Оформить заказ
         * @description Повтор с тем же непустым idempotencyKey для клиента возвращает прежний заказ. Цена и остаток проверяются сервером.
         */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Мои заказы */
        get: operations["listMyOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/my/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        /** Подробности заказа */
        get: operations["getMyOrder"];
        /** Изменить получателя или получение до подтверждения */
        put: operations["updatePendingOrder"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/my/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отменить заказ */
        post: operations["cancelMyOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/my/{id}/returns": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать заявку на возврат доставленного заказа */
        post: operations["createOrderReturn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/promotions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Активные акции */
        get: operations["listPromotions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/promo/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Проверить промокод */
        post: operations["validatePromo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/loyalty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Баланс и история бонусов */
        get: operations["getLoyaltyAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/delivery/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Рассчитать получение */
        post: operations["quoteDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Доступные магазины для самовывоза */
        get: operations["listPickupStores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Заказы всех клиентов */
        get: operations["listAdminOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Клиенты с итогами заказов и бонусами */
        get: operations["listAdminUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/admin/promotions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Все промокоды */
        get: operations["listAdminPromotions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/admin/returns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Заявки на возврат всех клиентов */
        get: operations["listAdminReturns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/admin/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Показатели магазина */
        get: operations["getAdminAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Уведомления клиента */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Число непрочитанных уведомлений */
        get: operations["countUnreadNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Пометить своё уведомление прочитанным */
        patch: operations["markNotificationRead"];
        trace?: never;
    };
    "/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Подписаться на новости; вход необязателен */
        post: operations["subscribeNewsletter"];
        /** Отписаться от новостей */
        delete: operations["unsubscribeNewsletter"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Статус подписки клиента */
        get: operations["getSubscriptionStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Message: {
            message?: string;
        };
        ApiError: {
            /** @description Стабильный машинный код, например BAD_REQUEST, NOT_FOUND или INVALID_TOKEN */
            code: string;
            message: string;
            fieldErrors: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            requestId: string;
            /** Format: date-time */
            timestamp: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            firstName: string;
            lastName: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        AuthResponse: {
            /** Format: uuid */
            uuid: string;
            /** Format: email */
            email: string;
            firstName?: string;
            lastName?: string;
            phone?: string | null;
            role: string;
            /** @description JWT после входа; null при регистрации */
            token: string | null;
        };
        UserProfile: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            firstName?: string;
            lastName?: string;
            phone?: string | null;
            /** Format: date */
            birthday?: string | null;
            avatar?: string | null;
            role: string;
        };
        UpdateProfileRequest: {
            /** Format: email */
            email: string;
            firstName: string;
            lastName: string;
            phone?: string;
            /** Format: date */
            birthday?: string;
            avatar?: string;
        };
        ChangePasswordRequest: {
            /** Format: password */
            currentPassword: string;
            /** Format: password */
            newPassword: string;
        };
        ProductUuidRequest: {
            /** Format: uuid */
            id: string;
        };
        Product: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string | null;
            price: number;
            gender?: string | null;
            imageUrl?: string | null;
            rating?: number;
            reviewCount?: number;
            categories?: string[];
            colors?: components["schemas"]["ProductColor"][];
            stock?: components["schemas"]["ProductStock"][];
        };
        ProductColor: {
            /** Format: uuid */
            id?: string;
            name?: string;
            hexCode?: string;
        };
        ProductStock: {
            /** Format: uuid */
            sizeId?: string;
            sizeName?: string;
            sizeType?: string;
            sizeGender?: string;
            sizeDescription?: string;
            /** Format: uuid */
            colorId?: string;
            colorName?: string;
            quantity?: number;
        };
        AdminVariants: {
            colors: components["schemas"]["ProductColor"][];
            sizes: components["schemas"]["AdminSize"][];
        };
        AdminSize: {
            /** Format: uuid */
            id: string;
            name: string;
            type: string;
            gender?: string | null;
            region?: string | null;
            description?: string | null;
        };
        OrderItemRequest: {
            /** Format: uuid */
            productId: string;
            /** Format: uuid */
            colorId: string;
            /** Format: uuid */
            sizeId: string;
            quantity: number;
        };
        CreateOrderRequest: {
            customerName?: string;
            /** Format: email */
            customerEmail?: string;
            /** @description Если не передан, сервер берёт телефон из профиля; в итоге телефон обязателен */
            customerPhone?: string;
            /** @description Адрес доставки или название/адрес магазина самовывоза */
            address: string;
            /** @enum {string} */
            deliveryMethod?: "courier" | "pickup";
            /** @enum {string} */
            paymentMethod?: "CARD" | "SBP" | "ON_RECEIPT";
            /** @description Ключ идемпотентности передаётся в JSON-теле, не в HTTP-заголовке */
            idempotencyKey?: string;
            promoCode?: string | null;
            bonusesToUse?: number;
            items: components["schemas"]["OrderItemRequest"][];
        };
        Order: {
            /** Format: uuid */
            id: string;
            orderNumber: string;
            /** Format: uuid */
            userId?: string;
            customerName?: string;
            customerEmail?: string;
            customerPhone?: string;
            /** @enum {string} */
            status: "PENDING" | "CONFIRMED" | "ASSEMBLING" | "SHIPPED" | "DELIVERED" | "CANCELLED";
            subtotal?: number;
            discountAmount?: number;
            bonusesUsed?: number;
            bonusesEarned?: number;
            promoCode?: string | null;
            totalAmount: number;
            /** Format: date-time */
            createdAt?: string;
            items?: components["schemas"]["OrderItem"][];
        };
        OrderDetail: components["schemas"]["Order"] & {
            delivery?: {
                [key: string]: unknown;
            } | null;
            payment?: {
                [key: string]: unknown;
            } | null;
            returns?: {
                [key: string]: unknown;
            }[];
            events?: {
                [key: string]: unknown;
            }[];
        };
        OrderItem: {
            /** Format: uuid */
            productId?: string;
            /** Format: uuid */
            colorId?: string;
            colorName?: string | null;
            /** Format: uuid */
            sizeId?: string;
            sizeName?: string | null;
            name?: string;
            imageUrl?: string;
            quantity?: number;
            price?: number;
        };
        UpdatePendingOrderRequest: {
            customerName?: string;
            /** Format: email */
            customerEmail?: string;
            customerPhone?: string;
            address: string;
            /** @enum {string} */
            deliveryMethod?: "courier" | "pickup";
        };
        CreateReturnRequest: {
            /** @enum {string} */
            reason: "SIZE" | "QUALITY" | "WRONG_ITEM" | "OTHER";
            comment?: string;
        };
        OrderReturn: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orderId: string;
            reason: string;
            comment?: string | null;
            status: string;
            refundAmount: number;
            /** Format: date-time */
            createdAt: string;
        };
        AdminUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            firstName?: string | null;
            lastName?: string | null;
            phone?: string | null;
            /** Format: date */
            birthday?: string | null;
            role: string;
            /** Format: date-time */
            createdAt?: string;
            bonusBalance: number;
            orderCount: number;
            orderTotal: number;
        };
        AdminPromotion: {
            /** Format: uuid */
            id: string;
            code: string;
            title: string;
            description?: string | null;
            active: boolean;
            usage_count?: number;
            discount_percent?: number;
            bonus_multiplier?: number;
            min_order?: number;
            birthday_only?: boolean;
        };
        AdminReturn: {
            /** Format: uuid */
            id: string;
            orderNumber: string;
            /** Format: email */
            email: string;
            reason: string;
            comment?: string | null;
            status: string;
            refund_amount: number;
            /** Format: date-time */
            created_at: string;
        };
        AdminAnalytics: {
            orders: {
                total: number;
                last30Days: number;
                revenue: number;
            };
            returns: {
                total: number;
                requested: number;
            };
            lowStock: number;
            topProducts: {
                /** Format: uuid */
                id: string;
                name: string;
                quantity: number;
                revenue: number;
            }[];
        };
        CategoryNode: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            parentId?: string | null;
            children: components["schemas"]["CategoryNode"][];
        };
        Promotion: {
            /** Format: uuid */
            id?: string;
            code?: string;
            title?: string;
            description?: string;
            discountPercent?: number;
            bonusMultiplier?: number;
            minOrder?: number;
            birthdayOnly?: boolean;
            /** Format: date-time */
            validUntil?: string | null;
        };
        ValidatePromoRequest: {
            code: string;
            subtotal?: number;
        };
        SaveReviewRequest: {
            rating: number;
            qualityRating?: number;
            /** @enum {string} */
            fit?: "SMALL" | "AS_EXPECTED" | "LARGE";
            photoUrl?: string;
            body: string;
        };
        ProductReview: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            userId?: string;
            authorName?: string;
            rating?: number;
            qualityRating?: number;
            fit?: string;
            photoUrl?: string | null;
            verifiedPurchase?: boolean;
            body?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        LoyaltyAccount: {
            balance?: number;
            lifetimeEarned?: number;
            tier?: string;
            /** Format: date-time */
            updatedAt?: string;
            birthdayToday?: boolean;
            birthdayBenefit?: string;
            transactions?: components["schemas"]["LoyaltyTransaction"][];
        };
        LoyaltyTransaction: {
            amount?: number;
            type?: string;
            description?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        DeliveryQuoteRequest: {
            /** @enum {string} */
            method?: "courier" | "pickup";
            subtotal?: number;
        };
        DeliveryQuote: {
            /** @enum {string} */
            method?: "courier" | "pickup";
            cost?: number;
            estimatedDays?: number;
            provider?: string;
        };
        PickupStore: {
            /** Format: uuid */
            id?: string;
            name?: string;
            city?: string;
            address?: string;
            phone?: string | null;
            hours?: string | null;
            latitude?: number | null;
            longitude?: number | null;
            active?: boolean;
        };
        Notification: {
            /** Format: uuid */
            id: string;
            recipientUuid?: string;
            type: string;
            title: string;
            message: string;
            read: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        UnreadNotificationCount: {
            count: number;
        };
        MarkNotificationReadResult: {
            read: boolean;
        };
        SubscribeRequest: {
            /** Format: email */
            email: string;
        };
        SubscriptionStatus: {
            active: boolean;
            /** Format: email */
            email?: string;
        };
    };
    responses: {
        /** @description Нет токена, JWT неверен или указаны неверные учётные данные */
        Unauthorized: {
            headers: {
                /** @description Доверенный ID запроса */
                "X-Request-Id"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Некорректный запрос */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Нет прав администратора */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Ресурс не найден */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        OrderId: string;
        ResourceId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Создан аккаунт; JWT выдаётся при последующем входе */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    loginCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Выдан JWT */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Профиль */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Обновлённый профиль */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Пароль изменён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список товаров */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"][];
                };
            };
        };
    };
    listAdminVariants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Доступные цвета и размеры */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminVariants"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getProductByUuid: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUuidRequest"];
            };
        };
        responses: {
            /** @description Товар */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getCategoryTree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Дерево категорий */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryNode"][];
                };
            };
        };
    };
    listProductReviews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Отзывы */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductReview"][];
                };
            };
        };
    };
    saveProductReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveReviewRequest"];
            };
        };
        responses: {
            /** @description Сохранённый отзыв */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductReview"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Заказ создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listMyOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Заказы клиента */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMyOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Заказ, состав, получение, оплата и события */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updatePendingOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePendingOrderRequest"];
            };
        };
        responses: {
            /** @description Обновлённый заказ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    cancelMyOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Отменённый заказ; повторная отмена безопасна */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createOrderReturn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReturnRequest"];
            };
        };
        responses: {
            /** @description Заявка создана */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderReturn"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listPromotions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Акции */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Promotion"][];
                };
            };
        };
    };
    validatePromo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidatePromoRequest"];
            };
        };
        responses: {
            /** @description Данные применимого промокода */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getLoyaltyAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Программа лояльности клиента */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoyaltyAccount"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    quoteDelivery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeliveryQuoteRequest"];
            };
        };
        responses: {
            /** @description Стоимость и срок; сейчас используется заглушка доставки */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryQuote"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listPickupStores: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Активные магазины */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PickupStore"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listAdminOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Заказы */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listAdminUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Клиенты */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listAdminPromotions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Промокоды */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPromotion"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listAdminReturns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Заявки */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminReturn"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getAdminAnalytics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Показатели */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAnalytics"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listNotifications: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Последние уведомления */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    countUnreadNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Число непрочитанных */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnreadNotificationCount"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    markNotificationRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Уведомление прочитано */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkNotificationReadResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    subscribeNewsletter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscribeRequest"];
            };
        };
        responses: {
            /** @description Подписка активна */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionStatus"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    unsubscribeNewsletter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Подписка отключена */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSubscriptionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Текущий статус */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
